import sys

with open('App.vue', 'r') as f:
    content = f.read()

replacements = {
    # UI Text
    'En attente de la carte...': 'Waiting for map...',
    'Connecté à ROSBridge !': 'Connected to ROSBridge!',
    'Erreur de connexion ROS': 'ROS connection error',
    'Déconnecté de ROSBridge': 'Disconnected from ROSBridge',
    "Erreur d'import ou de connexion": 'Import or connection error',
    'Taille :': 'Size:',
    'Résolution:': 'Resolution:',
    'Batterie critique :': 'Critical battery:',
    "Batterie vide ! Le robot s'est arrêté.": "Empty battery! Robot stopped.",
    "Erreur d'écriture InfluxDB :": 'InfluxDB write error:',
    'Historique Analytics': 'Analytics History',
    'Historique InfluxDB (Session complète)': 'InfluxDB History (Full Session)',
    'Batterie': 'Battery',
    'Vitesses': 'Speeds',
    'Linéaire': 'Linear',
    'Angulaire': 'Angular',
    'Trajectoire (X/Y)': 'Trajectory (X/Y)',
    'Position (Temps)': 'Position (Time)',
    'Fermer': 'Close',
    'Caméra Robot': 'Robot Camera',
    'Flux Vidéo ROS2': 'ROS2 Video Stream',
    'Attente du premier scan...': 'Waiting for first scan...',
    "Arrêt d'Urgence": 'Emergency Stop',
    'VITESSE LINÉAIRE': 'LINEAR SPEED',
    'VITESSE ANGULAIRE': 'ANGULAR SPEED',
    'Carte Live (SLAM)': 'Live Map (SLAM)',
    'Vide': 'Empty',
    'Obstacle': 'Obstacle',
    'Contrôle Manuel': 'Manual Control',
    'Vitesse Max (Avant) :': 'Max Speed (Linear):',
    'Vitesse Max (Rotation) :': 'Max Speed (Angular):',
    'Onglet': 'Tab',

    # Comments (Vue/JS)
    '// --- CONFIGURATION INFLUXDB ---': '// --- INFLUXDB CONFIGURATION ---',
    "// Utilisation de l'ID exact de votre organisation": '// Using the exact ID of your organization',
    '// ms = Précision à la milliseconde': '// ms = Millisecond precision',
    "// Nos variables réactives (si elles changent, l'interface se met à jour)": '// Reactive variables (if they change, the UI updates)',
    '// Batterie a 100% au départ': '// Battery at 100% at startup',
    "// Vitesse d'avance (m/s)": '// Linear speed (m/s)',
    '// Vitesse de rotation (rad/s)': '// Angular speed (rad/s)',
    "// État du bouton d'arrêt d'urgence": '// Emergency stop button state',
    '// tableau vide au départ': '// empty array at startup',
    "// Controle de l'affichage du LiDAR": '// LiDAR display control',
    '// 1 = 100%, 0.5 = 50% (dézoom), 2 = 200% (zoom)': '// 1 = 100%, 0.5 = 50% (zoom out), 2 = 200% (zoom in)',
    '// Variable pour savoir quel onglet est ouvert': '// Variable to know which tab is open',
    '// Données partagées pour le modal agrandi': '// Shared data for the expanded modal',
    "// L'objet qui gérera la connexion": '// The object that will manage the connection',
    "// Ajouté pour éviter l'erreur dans disconnectRos": '// Added to prevent error in disconnectRos',
    "// On récupère l'heure du dernier reset depuis le localStorage (survit au rafraîchissement)": '// Retrieve the last reset time from localStorage (survives refresh)',
    "// ---- SOLUTION D'EXPERT : Web Worker pour la Carte ----": '// ---- EXPERT SOLUTION: Web Worker for the Map ----',
    "// Création d'un Worker dynamique pour calculer l'image de la carte en arrière-plan (sans bloquer l'UI)": '// Create a dynamic Worker to calculate the map image in the background (without blocking the UI)',
    '// Inconnu (Gris foncé)': '// Unknown (Dark gray)',
    '// Vide (Gris très clair)': '// Empty (Very light gray)',
    '// Mur / Obstacle (Rouge vif)': '// Wall / Obstacle (Bright red)',
    '// On renvoie le tableau calculé au fil principal': '// Send the calculated array back to the main thread',
    '// Variable réactive pour la position du robot': '// Reactive variable for the robot position',
    '// ----- Batterie et Data Historian -----': '// ----- Battery and Data Historian -----',
    '// 1. DÉCHARGE SIMULÉE DE LA BATTERIE': '// 1. SIMULATED BATTERY DISCHARGE',
    '// Calcul : 100% / 10800 secondes (3h) ≈ 0.0093% par seconde': '// Calculation: 100% / 10800 seconds (3h) ≈ 0.0093% per second',
    '// 2. BOUCLIER DE SÉCURITÉ': '// 2. SAFETY SHIELD',
    '// ⚠️ AVIS ARCHITECTURE ROS2 :': '// ⚠️ ROS2 ARCHITECTURE NOTICE:',
    '// Gérer la sécurité depuis le Dashboard web est dangereux (risque de perte de Wi-Fi ou plantage navigateur).': '// Managing safety from the web Dashboard is dangerous (risk of Wi-Fi loss or browser crash).',
    '// Dans un vrai système, cette logique de "bouclier" (blocage cmd_vel) doit être implémentée': '// In a real system, this "shield" logic (blocking cmd_vel) must be implemented',
    '// dans un nœud ROS2 embarqué (C++ ou Python) directement sur le robot.': '// in an embedded ROS2 node (C++ or Python) directly on the robot.',
    '// 3. ENVOI DES DONNÉES À INFLUXDB (Data Historian)': '// 3. SEND DATA TO INFLUXDB (Data Historian)',
    '// Calcul du capteur de proximité virtuel (Lidar)': '// Virtual proximity sensor calculation (Lidar)',
    "// S'il n'y a pas de point valide, on met une valeur par défaut de 10 mètres": '// If there is no valid point, set a default value of 10 meters',
    '// Le nom de la "table"': '// The name of the "table"',
    '// Étiquette pour identifier ce robot spécifique': '// Tag to identify this specific robot',
    '// État du robot (MOVING, IDLE, OFFLINE)': '// Robot state (MOVING, IDLE, OFFLINE)',
    "// NOUVEAU: Arrêt d'urgence": '// NEW: Emergency stop',
    '// NOUVEAU: Pare-chocs virtuel Lidar': '// NEW: Lidar virtual bumper',
    '// On met le point dans la boîte aux lettres': '// Put the point in the mailbox',
    '// Optimisation : On ne force plus le flush() à chaque seconde.': '// Optimization: We no longer force flush() every second.',
    '// On laisse le client InfluxDB grouper (batch) les envois en arrière-plan pour de meilleures performances.': '// We let the InfluxDB client batch the sends in the background for better performance.',
    "// ----- Gestion des États et de l'UI -----": '// ----- State and UI Management -----',
    "// Détecter l'état via la réception de données brutes est imprécis.": '// Detecting state via raw data reception is imprecise.',
    "// La bonne pratique (Standard ROS2) est d'utiliser `diagnostic_msgs` sur le topic `/diagnostics`": '// The best practice (ROS2 Standard) is to use `diagnostic_msgs` on the `/diagnostics` topic',
    "// où le robot publie un \"Heartbeat\" officiel de l'état de chaque composant (OK, WARN, ERROR).": '// where the robot publishes an official "Heartbeat" of each component\'s state (OK, WARN, ERROR).',
    '//État de santé des capteurs': '// Sensor health state',
    "// Déduire l'état uniquement à partir de la vitesse (odom) est une approche limitée.": '// Deducing state solely from speed (odom) is a limited approach.',
    '// Si le robot est bloqué physiquement mais que les moteurs tournent, le dashboard affichera "MOVING".': '// If the robot is physically blocked but the motors are running, the dashboard will show "MOVING".',
    '// L\'approche industrielle : utiliser les Managed Nodes (Lifecycle) ou écouter le serveur': '// The industrial approach: use Managed Nodes (Lifecycle) or listen to the',
    "// d'action de navigation (ex: Nav2) pour connaître le véritable état logique du robot.": '// navigation action server (e.g., Nav2) to know the true logical state of the robot.',
    "// L'état du robot se calcule tout seul en fonction de la vitesse !": '// The robot state calculates itself based on speed!',
    '//Repos': '//Idle',
    "// On crée une fonction pour obtenir le style CSS en fonction de l'état": '// We create a function to get the CSS style based on the state',
    '// Vert': '// Green',
    '// Orange': '// Orange',
    '// Rouge': '// Red',
    '// ----- Fonction Centrale de Connexion ROS (connectRos) -----': '// ----- Central ROS Connection Function (connectRos) -----',
    '// Création de la connexion vers': '// Creation of the connection to',
    '// Événement : Connexion réussie': '// Event: Connection successful',
    '// ---- PUBLISHER /cmd_vel ----': '// ---- PUBLISHER /cmd_vel ----',
    '// ---- ABONNEMENT À /odom ----': '// ---- SUBSCRIPTION TO /odom ----',
    "// On n'extrait plus que les vitesses depuis /odom (l'odométrie pure dérive)": '// We only extract speeds from /odom (pure odometry drifts)',
    '// ---- ABONNEMENT À /robot_pose (Position exacte sur la Carte SLAM) ----': '// ---- SUBSCRIPTION TO /robot_pose (Exact Position on SLAM Map) ----',
    '// Extraction de la position X et Y sur la map': '// Extraction of X and Y position on the map',
    "// Extraction de l'angle Yaw": '// Extraction of Yaw angle',
    '// ---- ABONNEMENT À /map ----': '// ---- SUBSCRIPTION TO /map ----',
    '// ---- ABONNEMENT AU LIDAR ----': '// ---- SUBSCRIPTION TO LIDAR ----',
    '// Événement : Erreur': '// Event: Error',
    '// Événement : Déconnexion': '// Event: Disconnection',
    '// ---- ABONNEMENT AU DIAGNOSTICS (Heartbeat Capteurs) ----': '// ---- SUBSCRIPTION TO DIAGNOSTICS (Sensor Heartbeat) ----',
    '// message.status est une liste (array) de tous les capteurs': '// message.status is an array of all sensors',
    "// Traduction du niveau d'erreur ROS2 (0=OK, 1= WARN, 2=ERROR, 3=STALE)": '// Translation of ROS2 error level (0=OK, 1=WARN, 2=ERROR, 3=STALE)',
    "// On met à jour l'état visuel pour l'interface": '// We update the visual state for the interface',
    "// ---- METHODES D'ACTIONS ----": '// ---- ACTION METHODS ----',
    "// Empêcher l'affichage du menu contextuel sur un clic droit": '// Prevent displaying context menu on right click',
    "// Plugin pour forcer un fond blanc (utile pour l'export PNG)": '// Plugin to force a white background (useful for PNG export)',
    '// Dessine le point (0 = invisible)': '// Draw the point (0 = invisible)',
    '// Masquer la grille': '// Hide the grid',
    '// Valeur max pour que le graphique ne saute pas tout le temps': '// Max value so the graph doesn\'t jump constantly',
    "// Évite l'effet accordéon": '// Prevents accordion effect',
    '// Dessine la ligne de la trajectoire': '// Draw the trajectory line',
    '// ---- INITIALISATION ----': '// ---- INITIALIZATION ----',
    '// Au montage du composant': '// On component mount',
    '// Fermer la connexion proprement quand on quitte la page': '// Close connection cleanly when leaving the page',
    '// 1. LE MENU DES ONGLETS': '// 1. TABS MENU',
    '// 2. ONGLET ANALYTICS': '// 2. ANALYTICS TAB',
    "// Barre d'outils globale": '// Global toolbar',
    '// Grille 2x2 des graphiques': '// 2x2 Graphics grid',
    '<!-- Modale de graphique agrandi -->': '<!-- Expanded graph modal -->',
    '<!-- 3. ONGLET CONTROL : GRID PRINCIPALE (Contient les 3 colonnes de notre dashboard) -->': '<!-- 3. CONTROL TAB: MAIN GRID (Contains the 3 columns of our dashboard) -->',
    '<!-- Colonne GAUCHE (Données en direct) -->': '<!-- LEFT Column (Live data) -->',
    '<!-- CARTE : SYSTEM STATUS-->': '<!-- CARD: SYSTEM STATUS -->',
    '<!-- Colonne CENTRE (Visualisation Principale) -->': '<!-- CENTER Column (Main Visualization) -->',
    '<!-- Curseur de Zoom -->': '<!-- Zoom slider -->',
    "<!-- C'est ici qu'on va dessiner la carte avec le zoom et le blocage des débordements -->": '<!-- This is where we will draw the map with zoom and overflow blocking -->',
    '<!-- Colonne DROITE (Contrôles Actifs) -->': '<!-- RIGHT Column (Active Controls) -->',
    '<!-- Contrôle Manuel -->': '<!-- Manual Control -->',
    '<!-- On mettra les événements ici -->': '<!-- Events will be put here -->',
    '/* Thème très sombre / Espace */': '/* Very dark theme / Space */',
    '/* Polices et réinitialisation */': '/* Fonts and reset */',
    '/* Barre supérieure transparente */': '/* Transparent top bar */',
    '/* Layout principal en 3 colonnes */': '/* Main layout in 3 columns */',
    '/* Pour masquer le scroll de la colonne */': '/* To hide column scroll */',
    '/* Cartes (fonds gris) */': '/* Cards (gray background) */',
    '/* Boutons de Contrôle */': '/* Control Buttons */',
    '/* Boutons */': '/* Buttons */',
    '/* Badges de statut */': '/* Status badges */',
    "// On enregistre l'heure du reset dans le localStorage pour le garder après un rafraîchissement": '// We save the reset time in localStorage to keep it after a refresh',
    "// On force la mise à jour immédiate du graphique avec un point à 100% à l'instant T": '// Force immediate update of the graph with a 100% point at time T',
    '// Le graphique se mettra à jour à la prochaine boucle fetchAndDrawChart': '// The graph will update on the next fetchAndDrawChart loop',
    '// ---- Coordonnées Spatiales ----': '// ---- Spatial Coordinates ----',
    '// Convertit des mėtres (Monde ROS) en pixels (Canvas HTML)': '// Converts meters (ROS World) to pixels (HTML Canvas)',
    "// ----- Le Chef d'Orchestre Graphique (renderCanvas) -----": '// ----- The Graphical Conductor (renderCanvas) -----',
    "// Le chef d'orchestre qui superpose tout !": '// The conductor who overlays everything!',
    '// Couche 1 : On colle le fond (la carte)': '// Layer 1: Paste the background (the map)',
    '// Couche 3 : On dessine le robot par dessus (Point Bleu)': '// Layer 3: Draw the robot on top (Blue Point)',
    '// 1. Le corps du robot (Cercle Bleu)': '// 1. The robot body (Blue Circle)',
    '// Bleu': '// Blue',
    '// 2. La flèche de direction (Ligne Noire)': '// 2. Direction arrow (Black Line)',
    '// On calcule un point virtuel situé 50 cm (0.5m) devant le robot': '// We calculate a virtual point 50 cm (0.5m) in front of the robot',
    '// Noir pour contraster avec le fond gris clair de la carte': '// Black to contrast with the light gray map background',
    '// Trait plus épais': '// Thicker stroke',
    '// ----- LA GAME LOOP (Optimisation Industrielle) -----': '// ----- THE GAME LOOP (Industrial Optimization) -----',
    '// Démarrage de la boucle infinie dès le chargement du script': '// Start the infinite loop as soon as the script loads',
    '// ----- Dashboard Analytique (InfluxDB -> Chart.js) -----': '// ----- Analytical Dashboard (InfluxDB -> Chart.js) -----',
    "// Formater l'heure pour le label X": '// Format time for X label',
    '// On met à jour les 4 graphiques principaux': '// We update the 4 main graphs',
    '// On met à jour le graphique agrandi si un est ouvert': '// We update the expanded graph if one is open',
    '// Récupération instantanée ! (Très performant)': '// Instant recovery! (Very performant)',
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open('App.vue', 'w') as f:
    f.write(content)

